added filter prototype in helpers.h
Blaze-Stars/Image-Filter-Beta pull request #42
Opened 2022-06-09 08:46 UTC by Tushar7-coder

2022-06-09 14:11 UTC, chandrakant100 commented on helpers.h
> +void sepia(int height,int width,RGBTRIPLE **image);
Are we going to use vectors?

2022-06-09 14:17 UTC, chandrakant100 requested changes

2022-06-11 05:01 UTC, chandrakant100 commented on helpers.h
> +  void grayscale(int ,int ,RGBTRIPLE);
Expected a double pointer in third argument i.3 `void grayscale(in, int, RGbTRIPLE **);`

2022-06-11 05:06 UTC, chandrakant100 requested changes

2022-06-11 05:06 UTC, chandrakant100 commented on helpers.h
> +  void grayscale(int ,int ,RGBTRIPLE);
Expected a double-pointer in third argument i.3 `void grayscale(int, int, RGbTRIPLE **);` 
Also, add proper spacing as I did.
This should be followed in all function prototypes.

2022-06-11 05:22 UTC, chandrakant100 commented
Everything looks great ! Let's wait for @Himanshu40 review.

2022-06-11 05:32 UTC, Himanshu40 commented on helpers.h
> +  void reflect(int ,int ,RGBTRIPLE);
```suggestion
void reflect(int , int , RGBTRIPLE **);
```
Please, maintain what I have suggested.

2022-06-11 05:36 UTC, Himanshu40 approved these changes
Everything is fine.

2022-06-11 05:38 UTC, chandrakant100 approved these changes

2022-06-11 05:38 UTC, Himanshu40 requested changes

2022-06-11 05:38 UTC, Himanshu40 commented on helpers.h
> + void sepia(int, int,RGBTRIPLE **);
```suggestion
 void sepia(int, int, RGBTRIPLE **);
```
You didn't add space? Also please add a new line every time you reach the end of the file.

2022-06-11 06:56 UTC, chandrakant100 approved these changes
Everything looks good! It is ready to merge.

2022-06-11 07:09 UTC, Himanshu40 approved these changes

2022-06-11 07:09 UTC, merged